### ISSUE TITLE
Site/Synonyms

### ISSUE THREAD

**Issue by Goldenfreddy0703** [proohit/find-my-anime#4]
Hey there, sorry to bother you but I just gotta say that find-my-anime has been super useful for the past few months, my team and my community uses your api to help get the right season number/part number and its been amazing.

I have 2 big questions.
1. Where do you guys get all your synonyms? Do you guys combine it with other anime sites? Is there a way to get all with one request? It's amazing.

2. From looking at the status page for the site, it looks like you guys suffered from a substantial amount of request which is very sad. Do you guys plan to get the site online again by anychance? It's been great for community and I'm amazed with it.

**Comment by proohit** [comment]
Hey and thanks for the note. I recognized this yesterday as well and will have to look into it if I have some spare time. Do you mind sharing how much of load you need for the server? I rented a very limited server for this project and it might be necessary to migrate to some other server hoster.

The synonyms are part of https://github.com/manami-project/anime-offline-database and the specifics are not published. As far as I know, the database includes merged synonyms of supported anime sites.

For your request regarding getting all synonyms: Do you have an example to explain what you want exactly? I might get into implementing it but I need to know what you need exactly. Do you mean something like `GET api/synonyms` and that returns a list of all synonyms by anime? 

E. g. 

```json
[
   {"title": "anime1", "synonyms": [...]}, 
   {"title": "anime2", "synonyms": [...]}
]
```

**Comment by Goldenfreddy0703** [comment]
Hey thank you very much for responding, about how much of load i need for the server, we are actually pretty fine where it was originally at cause we don't use alot of request sense we cache them sometimes for the users to make loading faster and easier. 

About getting all synonyms, there is really nothing i really need exactly as long as find-my-anime api is working. The synonyms you guys have are very useful cause they help us find out if its part or cour or season and it helps us significantly when getting the number. I really appreciate using this api, its amazing and very useful. 

> Do you mean something like GET api/synonyms and that returns a list of all synonyms by anime?
Well kinda but im fine just getting all the information by anime so no need to implant the GET api/synonyms. Thank you very much though. 

Also huge thank you for telling me where you guys get the synonyms. They are very useful and a big help.
Thank you
