### ISSUE TITLE
[Question] Do you guys have a limit of how many request i can make?

### ISSUE THREAD

**Issue by Goldenfreddy0703** [proohit/find-my-anime#5]
Hey there, its me again and i have a huge question to ask. I want to use your api to use Mal Posters but it would take 50 request per anime page for every user if they have there settings configured to use mal posters. Would it be alright to use your api for that or would that use up too many request? 

If it does use too many request, i can possibly try to make a database file of the anime-offline-database, it would just take some time to work on.

**Comment by Goldenfreddy0703** [comment]
Hey so about what, i said, nevermind on this. Looks like loading speed was a bit too slow unfortunately but thats ok. I should have tested first before asking, Thank you and sorry to bother you.

**Comment by proohit** [comment]
Hey, I could also provide an endpoint to you so that you only have to send 1 request instead of 50, if that helps you. But for that, we would have to disucss the requirements more in detail.

**Comment by Goldenfreddy0703** [comment]
Hey, thank you very much for reaching out on this. Our addon is based off of the Anilist Database and we use Anilist's Graphql to help get most of the information. Every Menu item except watchlist loads a max page of 50 anime's per page. 

![code](https://github.com/proohit/find-my-anime/assets/62456796/c7062f05-a8f9-4ee1-a88a-26e9ba639cc5)
Our Addon is called Otaku and alot of our users use this addon for anime on kodi. We try our best to deliver quality and function. One feature i wanted to try to add was to have an option where users can decide on if they wanted Mal posters with clear logos in them sense Anilist does not have clear logos in there posters. 

If you would like to discuss the requirements more in detail.
Here is my contact information and my github project:

Discord: The Steampunk Owl#3126

Keybase: [Goldenfreddy0703](https://keybase.io/goldenfreddy0703)

Otaku: https://github.com/Goldenfreddy0703/Otaku

**Comment by proohit** [comment]
So you basically need a filter by multiple IDs that returns all results including given ids? Should be easily implementable. Will see if a comma separated list of IDs instead of a single id in the get query parameter will suffice.

**Comment by Goldenfreddy0703** [comment]
Ooo that would defiantly suffice. Thank you very much

Hopefully this will increase loading speed significantly. Thank you

**Comment by Goldenfreddy0703** [comment]
Heyyyy @proohit , sorry to bother you but its been about a week sense i replied, any updates so far on how the implementation is going so far? I don't need this feature right now but hopefully soon so it can be good to have in the future. 

If you could give me an update on this, that would be fantastic, thank you.

**Comment by proohit** [comment]
No update yet. Hopefully will find some time during the coming weekend

**Comment by Goldenfreddy0703** [comment]
Ahh ok sounds good, thank you!!!!!

**Comment by Goldenfreddy0703** [comment]
Heyyyy I know this issue has been opened for months but I already figured out a great solution so i should not need this opened any longer. Thank you for everything you have done. 

You're the best!!!!!!!!!
Thank you
