### ISSUE TITLE
[502 Bad Gateway] Looks like Find My Anime suddently went down today.

### ISSUE THREAD

**Issue by Goldenfreddy0703** [proohit/find-my-anime#6]
Hey @proohit so sorry to bother you but apparently we got a 502 error on your api. If you could have it fixed soon, that would be awesome. 

Thank you.

**Comment by proohit** [comment]
Yes I will have a look. I think the schema of the database changed and I need to adapt to that. I'm working right now though. Is it critical currently?

**Comment by Goldenfreddy0703** [comment]
Oh no its not critical at all but if you could get it online by tomorrow at any time, that would be fantastic. 
Btw that was a quick reply 😂

Thank you very much!!!!

**Comment by Goldenfreddy0703** [comment]
Hey no worries, it's totally fine, hopefully you will be able to find the issue pretty soon.

**Comment by proohit** [comment]
Hey @Goldenfreddy0703 is this issue still present?

**Comment by Goldenfreddy0703** [comment]
Oh no, I no I just forgot to close this. My bad. Thanks
