### ISSUE TITLE
Feature Request: Episode duration data is missing.

### ISSUE THREAD

**Issue by t9999clint** [proohit/find-my-anime#7]
I'm writing a linux app to identify and categorize my anime collection, but in order to help with that I'd like to compare the file's length to what's stored in the database.
I love this project and the ability to self host it if I want to. This lets me more easily cache the queries than aniList and other api's do so I've found it pretty useful so far.

However it looks like the episode duration information is missing. Is there any way to send a query to get this information as well? Or is this info not on your database?
If it's missing, I think it'd be super helpful if it was added. That way I wouldn't have to change my program to use aniList or something instead. I don't really like GraphQL so I'd really rather not have to deal with all that.

Regardless of your response I'd like to thank you for for hard work on this.

**Comment by proohit** [comment]
Hey and thanks for your feedback, glad to help:)

I've looked up your requested data. In the original offline database, episode length information are not provided. So we'd have to fetch it from any provider.

Anilist provides only a general episode length per anime (I suppose it's a mean for all), and not per episode. AniDB does provide lengths per episode, but only as integers, so no floating numbers (eg 25 [min]) Would that suffice for your use case?

**Comment by t9999clint** [comment]
Yeah that'd be more than enough.
I would be mostly using it for Movies, OVAs and specials, not really for TV series probably like 98% of those are 24min.
Should I also send a request for the offline database to add this data too? I also use their db in my project.

By the way I'm writing this entirely in Bash (3000 lines and growing). Mostly for the lawlz, but also because I can move it between servers without having to install/compile anything.
I'll share my code once I have it stable enough to be useful for normal people.

**Comment by proohit** [comment]
From experience they won't include any additional data requests.

**Comment by t9999clint** [comment]
That's a shame, looking it all up from a local file would be way better to use in terms of performance. Not to mention preventing any sort of accidental DDOS type scenario if I ever release this code and it gets used by a bunch of people. I plan on leaving the apiurl blank by default (probably just gonna leave a link to this github), hopefully that'll encourage people to use the docker container and not hammer your dtimur.de site

My main challenge this last week is trying to figure out how to properly handle caching requests. Not exactly something bash scripts are meant for. (I am a crazy person for doing it this way)

**Comment by proohit** [comment]
Hey @t9999clint , anime-offline-database recently added `duration` information to the database, which will now be included in the api. Please try out, if that fits your needs. I will close this for now, but feel free to open if you have any questions or issues.
