### ISSUE TITLE
[Bug] Not Kitsu in providerMapping field. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [proohit/find-my-anime#8]
Hey there, i was using your api for a bit and i found a small bug with your providerMapping field where Kitsu ID was not showing but it was showing in the sources field. Would this be considered a bug? 

If you can get back to me on that, that would be great!!!
Thanks

Also here is example of One Piece with all the sources including kitsu: 
![image](https://github.com/user-attachments/assets/283811e0-1110-45c5-887b-90dd358d72d6)

Here is an example of One Piece with all the Provider Mappings except Kitsu ID:
![image](https://github.com/user-attachments/assets/65b9c5cc-0668-4649-8514-7a6559f3da76)

**Comment by proohit** [comment]
Hey @Goldenfreddy0703 ,

Thanks for reporting. It seems like kitsu changed their domain to kitsu.app. I will fix and release this today.
